### ISSUE TITLE
Subscription does not expose basic cert-manager controller configurations

### ISSUE THREAD

**Issue by absynth76** [openshift/cert-manager-operator#200]
Using Subscription to install cert-manager does not permit to alter its configuration, among them:
- log level
- recursive names servers
- etc

everything is hardcoded in the csv and cannot be changed.

This is fairly limiting subscription usage and almost force everybody to use the helm chart or else to deploy.

related code is located within bindata.go
```
    spec:
      containers:
        - args:
            - --v=2
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --leader-election-namespace=kube-system
            - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.15.2
            - --max-concurrent-challenges=60
          command:
            - /app/cmd/controller/controller
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/jetstack/cert-manager-controller:v1.15.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
```

this is the issue when using OLM, you need to expose every capability over environment variables as it's done via the downward api with POD_NAMESPACE here.
